MASTER_IP = "10.156.0.2"
WORKER_IP = "10.156.0.3"

POD_NW_CIDR = "192.168.0.0/16"


Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = false


  config.vm.define "cks-master" do |master|

    master.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "cks-master"
      virtualbox.memory = 2048
      virtualbox.cpus = 2

      virtualbox.customize [
        "modifyvm", :id, "--uartmode1", "file",
        File.join(Dir.pwd, "tmp/cks-master.log")
      ]
    end
  
    master.vm.hostname = "cks-master"
    master.vm.network :private_network, ip: MASTER_IP
    master.vm.network "forwarded_port", guest: 22, host: 2710
    
    #for i in 30000..40000
    #  master.vm.network :forwarded_port, guest: i, host: i
    #end

    master.vm.provision "set-hosts", :type => "shell", :path => "setup/set-hosts.sh" do |s|
      s.args = ["enp0s8"]
    end

    master.vm.provision "update-dns", type: "shell", :path => "setup/update-dns.sh"


    #master.vm.provision :shell do |shell|
    #    shell.inline = "sudo chsh -s /bin/bash vagrant"
    #end
    
    master.vm.provision "install-master", type: "shell", :path => "setup/setup-master.sh", env: {"MASTER_IP" => "#{MASTER_IP}", "POD_NW_CIDR" => "#{POD_NW_CIDR}"}

    #master.vm.provision "install-master", type: "shell", :inline "kubeadm token create --print-join-command --ttl 0 > join.sh"

  end
  
  config.vm.define "cks-worker" do |worker|
      
  worker.vm.provider "virtualbox" do |virtualbox|
    virtualbox.name = "cks-worker"
    virtualbox.memory = 2048
    virtualbox.cpus = 2

    virtualbox.customize [
      "modifyvm", :id, "--uartmode1", "file",
      File.join(Dir.pwd, "tmp/cks-worker.log")
    ]

    end
    
    worker.vm.hostname = "cks-worker"
    worker.vm.network :private_network, ip: WORKER_IP
    worker.vm.network "forwarded_port", guest: 22, host: 2720
    
    worker.vm.provision "set-hosts", :type => "shell", :path => "setup/set-hosts.sh" do |s|
      s.args = ["enp0s8"]
    end
    
    
    worker.vm.provision "update-dns", type: "shell", :path => "setup/update-dns.sh"

    #worker.vm.provision :shell do |shell|
    #    shell.inline = "sudo chsh -s /bin/bash vagrant"
    #end

    worker.vm.provision "init-kubernetes", type: "shell", :path => "setup/setup-worker.sh"

  end

end
